server:
  port: 8180

spring:
  application:
    name: Spring-GraphQL
  
  graphql:
    graphiql:
      enabled: true
    path: /graphql
    cors:
      allowed-origins: "*"
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  datasource:
    url: jdbc:h2:mem:productdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
